name: CI
on:
  push:
    branches: [ "main"]
  

 
  workflow_dispatch:
env:
  message: "Have a good day"


jobs:
  
  job1:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3

      
      - name: Run a one-line script
        run: echo $message

      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  testing:
    
    runs-on: ubuntu-latest

  
    steps:
     
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, mywindows

      - name: Run a multi-line script
        run: |
          echo add my window server
          echo here i am testing my window
